# -*- coding: utf-8 -*-
"""final project coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgr_1Rq-Doo1LnUpEwvxC9b06PHpkUFz
"""

import pandas as pd
import geopandas as gpd
import folium


shopping_df = pd.read_csv("shopping_trends.csv")


category_data = shopping_df.groupby(['Location', 'Category']).agg({
    'Purchase Amount (USD)': 'mean',
    'Customer ID': 'count'
}).reset_index()
category_data.columns = ['state', 'category', 'avg_purchase', 'count']

us_states = gpd.read_file("cb_2022_us_state_20m.shp")
us_states = us_states[~us_states["STUSPS"].isin(["AK", "HI", "PR"])]

m = folium.Map(location=[39.5, -98.35], zoom_start=4, tiles="CartoDB positron")


for category in category_data['category'].unique():
    cat_df = category_data[category_data['category'] == category]
    merged = us_states.merge(cat_df, how="left", left_on="NAME", right_on="state")

    folium.Choropleth(
        geo_data=merged,
        name=category,
        data=merged,
        columns=["NAME", "avg_purchase"],
        key_on="feature.properties.NAME",
        fill_color="RdPu",
        fill_opacity=0.6,
        line_opacity=0.2,
        nan_fill_opacity=0.1,
        nan_fill_color="lightgray",
        legend_name=f"{category} - Avg Purchase",
        show=False
    ).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

m.save("shopping_trends_multilayer_map.html")
m